[project]
name = "flaskr"
version = "0.0.1"
description = "An application that randomly selects a movie."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"